name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8 & run tests & generate artifacts
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B clean test install
    - id: getfilename
      run: echo "::set-output name=file::$(ls target/symphony-dal-communicator-middleatlantic-*.jar)"
    - uses: actions/upload-artifact@v1
      with:
        path: ${{ steps.getfilename.outputs.file }}
